In [2]:
import numpy as np 

In [4]:
a = np.arange(1_000_000)

In [5]:
%%timeit 

a*a

922 µs ± 33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
rows, cols = 1_000, 1_000

a=[list (range (i, i+cols)) for i in range(rows)]
b=[[0 for j in range (cols)]for i in range (rows)]

In [14]:
%%timeit 

for i in range(rows): 
    for j in range(cols): 
        b[i][j] = 2 * a[i],[j]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
a = np.array ([1, 2, 3, 4, 5])
print (a)

In [ ]:
a.shape

In [3]:
import numpy as np 

In [15]:
a = np.array ([ 
    [1., 2., 3., 4., 5., 6.],
    [7., 8., 9., 10., 11., 12.]  ]
             )
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [5]:
a.size

12

In [6]:
count = a.size
item_size=a.dtype.itemsize
print(item_size)
#размер элемента массива - 8 байт 

8


In [7]:
#размер массива 
array_size = count*item_size 
print (array_size)

96


In [8]:
a, a.strides
#количество байт, на которые надо сместится в следующей строке
#размер элемента в байтах

(array([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]]),
 (48, 8))

In [9]:
a = np.array ([1, 2, 3, 4, 5], dtype=np.float32)
#частичная копия - не происходит копирования данных 
#отражаются изменения в изначальном массиве 
b=np.asarray(a)
#полная копия
# НЕ отражаются изменения в изначальном массиве 
c=np.array (a)
a[2]=-2
a,b,c

(array([ 1.,  2., -2.,  4.,  5.], dtype=float32),
 array([ 1.,  2., -2.,  4.,  5.], dtype=float32),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [10]:
#КОПИЯ С ИЗМЕНЕНИМ ТИПА ДАННЫХ 
b=np.asarray (a, dtype=np.int32)
a[1]=-1000
a,b

(array([    1., -1000.,    -2.,     4.,     5.], dtype=float32),
 array([ 1,  2, -2,  4,  5], dtype=int32))

In [13]:
a=np.array([1, 2, 3, 4, 5], dtype=np.float32)
b = a.view(np.int32)
#преобразование флоат в инт 

a[2]=-2
a,b

(array([ 1.,  2., -2.,  4.,  5.], dtype=float32),
 array([ 1065353216,  1073741824, -1073741824,  1082130432,  1084227584],
       dtype=int32))

In [29]:
#изменеие формы представления 
a = np.array ([ 
    [1., 2., 3., 4., 5., 6.],
    [7., 8., 9., 10., 11., 12.]  ]
             )
b = a.reshape(6, 2)
b, b.shape, b.strides 

(array([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]),
 (6, 2),
 (16, 8))

In [31]:
c = a.reshape(3, 2, 2)
c, c.shape, c.strides

(array([[[ 1.,  2.],
         [ 3.,  4.]],
 
        [[ 5.,  6.],
         [ 7.,  8.]],
 
        [[ 9., 10.],
         [11., 12.]]]),
 (3, 2, 2),
 (32, 16, 8))

In [32]:
a.reshape (-1,3)
# -1 означает количество строк вычисляется автоматеически 

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
b = a.reshape (3,-1)
a[0,1]=-10
a,b

(array([[  1., -10.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.,  12.]]),
 array([[  1., -10.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]]))

In [34]:
# flatten возвращает одномерный массив 

b = a.flatten() # data copy
a[0,1]=-20

a, b
#изменения не отображаются 

(array([[  1., -20.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.,  12.]]),
 array([  1., -10.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.]))

In [37]:
# ravel копия данных не выполняется 

b=a.ravel()
a[0,1]=-30

a,b
#изменения отображаются 

(array([[  1., -30.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.,  12.]]),
 array([  1., -30.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.]))

In [38]:
c = a.T #копия данных не выполняется 

a[0,1]=-40

a, c
# транспонирование - изменения отображаются 

(array([[  1., -40.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.,  12.]]),
 array([[  1.,   7.],
        [-40.,   8.],
        [  3.,   9.],
        [  4.,  10.],
        [  5.,  11.],
        [  6.,  12.]]))

In [39]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = b[np.newaxis, :]
#b.reshape(1, *b.shape) #синоним
b[2]=-20
b, a

(array([  0,   1, -20,   3,   4,   5,   6,   7,   8,   9]),
 array([[  0,   1, -20,   3,   4,   5,   6,   7,   8,   9]]))