In [2]:
import numpy as np

In [5]:
a = np.zeros (shape=(3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
b = np.zeros_like(a)#создание копии
a[0][1]=-0.1
a,b


(array([[ 0. , -0.1],
        [ 0. ,  0. ],
        [ 0. ,  0. ]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.eye(4)
# единичная матрица 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(1,10) #создание монотонных последовательностих 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [13]:
np.linspace(0,1, 5, endpoint = True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
a = np.arange (10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [17]:
a+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [18]:
3*a

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [19]:
a*a

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [20]:
np.sqrt(a) #корень из всех элементов массива 

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [21]:
2 ** a

array([[  1,   2,   4,   8,  16],
       [ 32,  64, 128, 256, 512]])

In [22]:
np.log (1+a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [23]:
np.log2(1+a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [24]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [25]:
np.greater(a,0) 

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [30]:
np.random.seed(128)
a=np.random.randint(0, 10, size=(7, ))
a[3]=10
a

array([ 2,  3,  5, 10,  7,  2,  4])

In [34]:
a.min(),a.max(),a.argmax(),a.sum(),a.prod(),a.mean() #среднее

(2, 10, 3, 33, 16800, 4.714285714285714)

In [35]:
np.random.seed(16)
a=np.random.randint (0, 10, size=(4,4))
a[2,2]=25
a

array([[ 9,  9,  5,  1],
       [ 4,  4,  9,  0],
       [ 0,  8, 25,  4],
       [ 0,  1,  2,  4]])

In [36]:
a.argmax() #порядковый номер в линейном исполнении

10

In [38]:
i = np.argmax(a)
i,j = i//a.shape[1], i% a.shape[1]
(i,j)
#index

(2, 2)

In [40]:
np.unravel_index(np.argmax(a),a.shape)
#index

(2, 2)

In [41]:
np.unravel_index(np.argmin(a),a.shape)

(1, 3)

In [42]:
np.random.seed(32)
a=np.random.randint (0, 10, size=(3,7))
a[1,3]=15
a

array([[ 7,  5,  6,  8,  3,  7,  9],
       [ 3,  5,  9, 15,  1,  3,  1],
       [ 2,  3,  8,  2,  4,  2,  4]])

In [43]:
a.max(axis=0)
#максимальные элементы по столбцам 

array([ 7,  5,  9, 15,  4,  7,  9])

In [44]:
a.max(axis=1)
#максимальные элементы по строкам

array([ 9, 15,  8])

In [45]:
a.sum(axis=1)
#сумма по строкам

array([45, 37, 25])

In [46]:
np.random.seed(8)
a=np.random.randint (0, 10, size=(4,2))
a[2,1]=21

np.random.seed(64)
b=np.random.randint (0, 10, size=a.shape)

a, b

(array([[ 3,  4],
        [ 1,  9],
        [ 5, 21],
        [ 3,  8]]),
 array([[4, 6],
        [7, 6],
        [6, 1],
        [4, 3]]))

In [47]:
a*b #поэлементное, а не матричное произведние 

array([[12, 24],
       [ 7, 54],
       [30, 21],
       [12, 24]])

In [48]:
a+b

array([[ 7, 10],
       [ 8, 15],
       [11, 22],
       [ 7, 11]])

In [49]:
np.fmax(a,b) #максимальные элементы по позиции

array([[ 4,  6],
       [ 7,  9],
       [ 6, 21],
       [ 4,  8]])

In [50]:
a>b

array([[False, False],
       [False,  True],
       [False,  True],
       [False,  True]])

In [52]:
a = np.asarray([True, True, False, False, True])
a

array([ True,  True, False, False,  True])

In [53]:
a.any() #есть хотя бы один элемент True

True

In [54]:
a.all() #все элементы True

False

In [55]:
a = np.asarray([[True, True, False, False, True], 
              [True, False, False, True, False]])
a, a.any(axis=0), a.all(axis=1)

(array([[ True,  True, False, False,  True],
        [ True, False, False,  True, False]]),
 array([ True,  True, False,  True,  True]),
 array([False, False]))

In [56]:
2+2

4

In [58]:
np.random.seed(8)
A = np.random.randint (0,5, size=(3,2))
B = np.random.randint (5,10, size=(2,3))
A, B

(array([[3, 4],
        [1, 1],
        [2, 0]]),
 array([[8, 5, 5],
        [9, 6, 8]]))

In [59]:
A@B #матричное умножение

array([[60, 39, 47],
       [17, 11, 13],
       [16, 10, 10]])

In [60]:
np.matmul(A, B) #матричное умножение

array([[60, 39, 47],
       [17, 11, 13],
       [16, 10, 10]])

In [62]:
np.random.seed(8)
a = np.random.randint (0,5, size=(4,))
b = np.random.randint (5,10, size=(4,))
a, b

(array([3, 4, 1, 1]), array([7, 5, 8, 5]))

In [63]:
np.dot (a, b), np.dot (A,B) #скалярное произведение 

(54,
 array([[60, 39, 47],
        [17, 11, 13],
        [16, 10, 10]]))

In [64]:
a@b np.matmul(A, B) 

54

In [69]:
A, B

(array([[12,  4],
        [ 1,  1],
        [ 2,  0]]),
 array([[24,  5,  5],
        [ 9,  6,  8]]))

In [70]:
C = np.asmatrix (A)  # matrix type 
D = np.matrix(B) # matrix type 
A [0][0]=12
B [0][0]=24
A,C,B,D

(array([[12,  4],
        [ 1,  1],
        [ 2,  0]]),
 matrix([[12,  4],
         [ 1,  1],
         [ 2,  0]]),
 array([[24,  5,  5],
        [ 9,  6,  8]]),
 matrix([[24,  5,  5],
         [ 9,  6,  8]]))

In [71]:
F = C * D  # matrix type 
F

matrix([[324,  84,  92],
        [ 33,  11,  13],
        [ 48,  10,  10]])

In [72]:
A, A ** 2 #каждый элемент возведен в квадрат 

(array([[12,  4],
        [ 1,  1],
        [ 2,  0]]),
 array([[144,  16],
        [  1,   1],
        [  4,   0]]))

In [73]:
 # matrix type 
F, F**2  #матричное возведение в степень 

(matrix([[324,  84,  92],
         [ 33,  11,  13],
         [ 48,  10,  10]]),
 matrix([[112164,  29060,  31820],
         [ 11679,   3023,   3309],
         [ 16362,   4242,   4646]]))

In [76]:
np.random.seed(512)
A = np.random.randint (0,5, size=(3,3))
A


array([[3, 1, 2],
       [1, 0, 0],
       [3, 2, 0]])

In [77]:
# определитель 
np.linalg.det(A)

4.0

In [79]:
A1 = np.linalg.inv(A)
A1
# обратная матрица

array([[ 0.  ,  1.  ,  0.  ],
       [ 0.  , -1.5 ,  0.5 ],
       [ 0.5 , -0.75, -0.25]])

In [80]:
A @ A1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
b = np.array([1, -2, 1])
A, b

(array([[3, 1, 2],
        [1, 0, 0],
        [3, 2, 0]]),
 array([ 1, -2,  1]))

In [82]:
x = np.linalg.solve(A,b)
x
# решение системных уравнений 

array([-2.  ,  3.5 ,  1.75])

In [84]:
A @ x # =b

array([ 1., -2.,  1.])

In [85]:
lam, V = np.linalg.eig(A)
lam, V

(array([ 4.67882303+0.j        , -0.83941152+0.38769081j,
        -0.83941152-0.38769081j]),
 array([[ 0.79497756+0.j        ,  0.45795361+0.13480762j,
          0.45795361-0.13480762j],
        [ 0.16990973+0.j        , -0.38851526-0.34003753j,
         -0.38851526+0.34003753j],
        [ 0.58235845+0.j        , -0.71101039+0.j        ,
         -0.71101039-0.j        ]]))

In [86]:
np.random.rand(10)

array([0.68233647, 0.32597119, 0.67656027, 0.88749116, 0.28003724,
       0.82334775, 0.16825266, 0.54987075, 0.2304416 , 0.99234406])

In [91]:
np.random.randint(0,10,10)

array([2, 3, 7, 4, 4, 8, 2, 2, 0, 8])

In [92]:
np.random.permutation(10)

array([9, 4, 8, 2, 7, 6, 1, 0, 3, 5])

In [94]:
np.random.seed(2048)
a = np.random.choice (10, size=(3,10))
a

array([[5, 7, 5, 9, 8, 6, 1, 2, 7, 8],
       [6, 9, 2, 7, 6, 0, 3, 9, 2, 4],
       [9, 1, 8, 3, 5, 2, 1, 0, 5, 6]])

In [95]:
np.sort(a.ravel()) # сортировка 

array([0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7,
       7, 8, 8, 8, 9, 9, 9, 9])

In [96]:
a.sort (axis=0) #по столбцам
a

array([[5, 1, 2, 3, 5, 0, 1, 0, 2, 4],
       [6, 7, 5, 7, 6, 2, 1, 2, 5, 6],
       [9, 9, 8, 9, 8, 6, 3, 9, 7, 8]])

In [97]:
a.sort (axis=1) #по строкам
a

array([[0, 0, 1, 1, 2, 2, 3, 4, 5, 5],
       [1, 2, 2, 5, 5, 6, 6, 6, 7, 7],
       [3, 6, 7, 8, 8, 8, 9, 9, 9, 9]])

In [98]:
a, a.argsort (axis=0)

(array([[0, 0, 1, 1, 2, 2, 3, 4, 5, 5],
        [1, 2, 2, 5, 5, 6, 6, 6, 7, 7],
        [3, 6, 7, 8, 8, 8, 9, 9, 9, 9]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]))

In [99]:
a, a.argsort (axis=0)

(array([[0, 0, 1, 1, 2, 2, 3, 4, 5, 5],
        [1, 2, 2, 5, 5, 6, 6, 6, 7, 7],
        [3, 6, 7, 8, 8, 8, 9, 9, 9, 9]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]))

In [100]:
np.unique(a) #уникальные элементы

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])