In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5]) 
a, type(a)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [3]:
a.shape

(5,)

In [4]:
tuple_1=("hello"); print (tuple_1) #не кортеж

hello


In [5]:
tuple_1=("hello",); print (tuple_1) #кортеж

('hello',)


In [6]:
a.dtype

dtype('int64')

In [8]:
a = np.array ([1., 2., 3., 4., 5.]) #вещественные числа
a, a.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [10]:
a = np.array ([1., 2., 3., 4., 5.], dtype=np.float32) 
#вещественные числа, тип данных устанавливаем сами 
a, a.dtype

(array([1., 2., 3., 4., 5.], dtype=float32), dtype('float32'))

In [12]:
a = np.arange(15) 
#the index starts with 0 and ends with n-1

a[10] = 100 #shange 10th element 

a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11,  12,
        13,  14])

In [13]:
a[len(a)-1], a[-1] #index from end

(14, 14)

In [15]:
#array[start=0: stop=len(array)-1:step=1]
#получить срез из массива 

In [20]:
a = np.arange(15)
variants = [a[1:5:2]]
variants

[array([1, 3])]

In [23]:
variants = a[slice(1, 5, 2)]
variants

array([1, 3])

In [25]:
variants = [a[0: :2]] #четные позиции
variants

[array([ 0,  2,  4,  6,  8, 10, 12, 14])]

In [26]:
variants = [a[1: :2]] #нечетные позиции
variants

[array([ 1,  3,  5,  7,  9, 11, 13])]

In [27]:
variants = [a[3:13:3][::-1]] #в обратном порядке 
variants

[array([12,  9,  6,  3])]

In [29]:
a = np.array([1, 2, 3, 4, 5])
mask = np.array ([False, True, True, False, True])
mask, a, a[mask]

(array([False,  True,  True, False,  True]),
 array([1, 2, 3, 4, 5]),
 array([2, 3, 5]))

In [31]:
np.random.seed(1024)

a = np.random.randint(-2, 7, 34) 
#минимальный элемент(-2)
#максимальный элемент(7)
#количество элементов (34)
a

array([-1, -1,  3, -1, -2, -2,  1,  0, -2,  5,  6,  5, -1,  0,  1,  3, -2,
        3,  3,  1, -2,  4,  4,  3,  4,  2,  2, -1, -2, -1,  6,  5, -2, -1])

In [32]:
a[a<0]

array([-1, -1, -1, -2, -2, -2, -1, -2, -2, -1, -2, -1, -2, -1])

In [33]:
variants = [ a[a%3 == 0], 
            a [np.logical_not (a%3)]]
variants

[array([3, 0, 6, 0, 3, 3, 3, 3, 6]), array([3, 0, 6, 0, 3, 3, 3, 3, 6])]

In [35]:
np.random.seed(1234)

a = np.random.randint(0, 9, 23) 

a

array([3, 6, 5, 4, 8, 1, 7, 6, 8, 0, 5, 0, 6, 2, 0, 5, 2, 6, 3, 7, 0, 0,
       3])

In [37]:
mask_3 = a % 3 == 0 
mask_5 = a % 5 == 0

variants = [a [np.logical_or(mask_3, mask_5)],
           a [mask_3 | mask_5]]
mask_3, mask_5, a, variants

(array([ True,  True, False, False, False, False, False,  True, False,
         True, False,  True,  True, False,  True, False, False,  True,
         True, False,  True,  True,  True]),
 array([False, False,  True, False, False, False, False, False, False,
         True,  True,  True, False, False,  True,  True, False, False,
        False, False,  True,  True, False]),
 array([3, 6, 5, 4, 8, 1, 7, 6, 8, 0, 5, 0, 6, 2, 0, 5, 2, 6, 3, 7, 0, 0,
        3]),
 [array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3]),
  array([3, 6, 5, 6, 0, 5, 0, 6, 0, 5, 6, 3, 0, 0, 3])])

In [38]:
mask = np.array ([True, True, False, True, False])
mask, np.where(mask)

(array([ True,  True, False,  True, False]), (array([0, 1, 3]),))

In [39]:
np.where(a>0) #индексы положительных элементов 

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 13, 15, 16, 17, 18, 19,
        22]),)

In [40]:
a = np.array ([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]]
             )
#список из списков с одинаковой длиной 
a, a.shape, a.dtype

(array([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]]),
 (2, 5),
 dtype('int64'))

In [41]:
a.ndim 
#количество измерений, размернось кортежа

2

In [43]:
a = np.arange(30).reshape(5, -1)
#пять строк (5), столбцов столько сколько нужно(-1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
#индексация без копирования
a[0,0], a[0,2], a[1,1], a[-1,-2]

(0, 2, 7, 28)

In [48]:
a[2],
a[2, :]
#строка с индексом 2 

array([12, 13, 14, 15, 16, 17])

In [49]:
a[:, 3]

array([ 3,  9, 15, 21, 27])

In [50]:
a[:,::2]
#по строкам все нам нужно 
#по столбцам - все элементы с шагом 2 
#получаем четные столбцы

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [51]:
a, a[1::2,2::3] [::-1]
# первый по последний с шагом два 
# со второго по последнюю с шагам три 
# обратная индексация 

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[20, 23],
        [ 8, 11]]))

In [52]:
a = np.arange(30).reshape(5, -1)
a, a[[2,4,3]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[12, 13, 14, 15, 16, 17],
        [24, 25, 26, 27, 28, 29],
        [18, 19, 20, 21, 22, 23]]))

In [53]:
# нулевая и последняя строка 
a, a[:,[0,-1]]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[ 0,  5],
        [ 6, 11],
        [12, 17],
        [18, 23],
        [24, 29]]))

In [55]:
# cross 2,4,5 and 0,5
a[[2,4,3]][:,[0,-1]]

array([[12, 17],
       [24, 29],
       [18, 23]])

In [57]:
a = np.arange(24).reshape(2, 3, 4)
# последовательность от 0 до 23, 
# массив из двух табличек размера 3 на 4
a, a[...,0], a[:,:,0]
#получаем все элементы с последним индексом 0
#первые столбцы

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  4,  8],
        [12, 16, 20]]),
 array([[ 0,  4,  8],
        [12, 16, 20]]))

In [58]:
a, a[0,:,:]
#певая табличка 

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [59]:
a, a[:,0,:] 
#первый номер строки 

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]))